### PR TITLE
Fix alert

### PR DESCRIPTION
**Pull request by totally-not-rous-alt**
it was broken

### CODE REVIEW

**Comment by vimproved** [comment]
no fuck you

**Comment by joshop** [comment]
I think this pull request requires a bit more consideration.

**Comment by joshop** [comment]
Personally I think this PR is a great idea

**Comment by joshop** [comment]
@joshop yes, I agree with you; this pull request deserves to be accepted

**Comment by joshop** [comment]
@joshop wow, this is such a great PR! Clearly, it deserves to be merged

**Comment by vimproved** [comment]
i swear to god i will rip out your spine and shove it up your ass

**Comment by joshop** [comment]
I think that we should reconsider this pull request. It has potential if done correctly.

**Comment by vimproved** [comment]
removed as contributor, take your greasy dick, chop it off, and use it to strangle a dead pig. let the pig sit for a year and eat it, then shit out diarrhea until you fucking die.

**Pull request closed without merging**
